[2024-06-24T08:06:35.311+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: dbt_snowflake_v03.dbt_run manual__2024-06-24T08:01:30.887821+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
